#ifndef CONFIG_ESP32_BIOSIGNALS_H
#define CONFIG_ESP32_BIOSIGNALS_H

#define ESP_GPIO_CS_SD 26
#define ESP_STIMULATION_VOLTAGE 39
#define ESP_SCLK 18
#define ESP_GPIO_ANALOG_DRDY 35
#define ESP_MISO 19
#define ESP_GPIO_RESET 33
#define ESP_MOSI 23
#define ESP_BAT_VOLTAGE 34
#define ESP_GPIO_CS_ANALOG_1 5
#define ESP_GPIO_WS2812B 13
#define ESP_SCL 22
#define ESP_SDA 21
#define ESP_IMU_INT 32
#define ESP_GPIO_CS_ANALOG_2 4


#endif // CONFIG_ESP32_BIOSIGNALS_H