name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flag_value: 
          - { value: 0, name: ADC_ADS131M08 }
          - { value: 1, name: ADC_AD7771 }

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio esptool

      - name: Build PlatformIO Project With ADC_USED And IMU_DISABLE Flag ${{matrix.flag_value.value}}
        env:
          PLATFORMIO_BUILD_FLAGS: -D ADC_USED=${{matrix.flag_value.value}} -D IMU_DISABLE=${{matrix.flag_value.value}}
        run: pio run
      
      - name: Copy firmware.bin to root directory
        run: cp .pio/build/**/firmware.bin firmware-ota.bin
      
      - name: Packing Firmware
        run: esptool.py --chip ESP32 merge_bin -o merged-flash.bin --flash_mode dio --flash_size 4MB 0x1000 .pio/build/**/bootloader.bin 0x8000 .pio/build/**/partitions.bin 0x10000 .pio/build/**/firmware.bin

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-BioListener-${{ matrix.flag_value.name }}
          path: |
            merged-flash.bin
            firmware-ota.bin
